apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-monitor
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-monitor
            image: final-image
            command: ["python", "health_check_script.py"]
          restartPolicy: OnFailure
